### PR TITLE
fix: stream export jobs to disk to bound memory (#208)

### LINKED ISSUE #208: Export jobs load entire dataset into memory — OOM risk for large exports
## Description

The export path in `api/src/main.rs` (`run_export_job`) and `api/src/export_worker.rs` loads ALL matching records into a `Vec<u8>` buffer in memory before writing to disk.

For large datasets (millions of records), this can exhaust available memory and crash the worker process, taking down all co-located workers.

## Impact

- A single large export job can OOM-kill the entire API server
- No back-pressure or streaming — memory grows linearly with dataset size
- No progress/resume for partially completed large exports

## Suggested Fix

Use streaming writes with cursor-based pagination (e.g. 10,000 records per batch), writing directly to disk.

## Files

- `api/src/main.rs` — `run_export_job`
- `api/src/export_worker.rs`

### PR DESCRIPTION
**Pull request by user1303836**
## Summary

Fixes #208. The old `run_export_job` loaded every matching record into a `Vec` and serialized the whole dataset into a single `Vec<u8>` before writing it to disk, so a single large export could OOM-kill the worker process and take down co-located workers.

The worker now streams the export directly to disk via `export_stream::write_export_to_file`, which fetches records in pages of 10,000 (`PAGE_SIZE`) via the existing paged `query_*` methods, serializes each page into a small per-page buffer, and writes the page into a `BufWriter<File>` opened with `O_NOFOLLOW` (preserves the #220 symlink-refusing open). Peak per-job memory is bounded by `PAGE_SIZE * per-record bytes` regardless of total dataset size.

## Key changes

- `api/src/export_stream.rs` (new) — paged dispatch for all 12 exportable datasets (`token_transfers`, `native_balance_deltas`, `decoded_events`, `hl_fills`, `hl_funding`, `positions`, `wallet_ledger`, `balance_history`, `hl_pnl_summary`, `hl_trade_history`, `protocol_events`, `pool_snapshots`), per-page serialization, async writes, and a 1M-record hard safety cap.
- `api/src/export_csv.rs` (new) — CSV header constants + `write_*_csv_rows<W: Write>` helpers shared between the streaming writer and the legacy test-only `*_to_csv` wrappers. Output is byte-identical to the pre-fix format — all `*_to_csv_format` tests continue to pass.
- `api/src/export_worker.rs` — builds the artifact path up front, calls the streaming writer, and on failure best-effort removes the partial file so retries do not append to a truncated artifact or hand out partial bytes via `/download`. Sink delivery reads the streamed artifact back from disk once for `sink.deliver(&[u8])` (converting `ExportSink` to take a path/reader is a follow-up).
- `api/src/main.rs` — drops `run_export_job` and the in-memory `*_to_csv` helpers that were only called from it; remaining `*_to_csv` wrappers are gated behind `#[cfg(test)]` and now delegate to the shared row writers in `export_csv`.

## Memory shape before / after

| Path | Before | After |
|---|---|---|
| No sink (download) | full dataset in `Vec<u8>` + written to disk | `PAGE_SIZE * record bytes` peak |
| With sink (local_file / webhook) | full dataset in `Vec<u8>` reused for disk + sink | bounded for disk write; sink still loads the artifact once for `sink.deliver(&[u8])` |

The sink case intentionally reads the artifact back for delivery to avoid changing the `ExportSink` trait signature in this PR. The disk write itself is now streamed, and the artifact size is bounded by `EXPORT_HARD_CAP` (1M records).

## Test plan

- [x] `cargo check --workspace --all-targets` clean
- [x] `cargo clippy --workspace --all-targets -- -D warnings` clean
- [x] `cargo fmt --all --check` clean
- [x] `cargo test --workspace --lib --bins` — 1104 tests pass, including all format-preserving `*_to_csv_format` tests, `test_serialize_to_jsonl`, `test_export_*` handler tests
- [ ] Docker-backed integration tests — could not be run locally (no container runtime on this machine); relying on CI

### CODE REVIEW

File: api/src/export_stream.rs [hunk 1]
```diff
@@ -0,0 +1,440 @@
...
+    (
+        $repo:expr, $writer:expr, $format:expr, $target_id:expr, $network:expr,
+        $time_start:expr, $time_end:expr, $query_fn:ident,
+        $csv_header_fn:path, $csv_rows_fn:path $(,)?
+    ) => {{
+        let mut offset: i64 = 0;
+        let mut total: usize = 0;
+        let mut write_header = true;
+        loop {
+            let records = $repo
```
Comment (user1303836) [inline api/src/export_stream.rs]: [P1] The streaming loop now performs a sequence of independent LIMIT/OFFSET queries, but the repository queries order only by non-unique timestamps/created_at and are not run under a stable snapshot/high-water mark. If tied rows straddle a page boundary, or if ingestion inserts matching rows while an export is running, rows can move between offsets and the artifact can skip or duplicate records. The old path was a single SELECT and did not have this cross-page correctness issue. Please make export pagination snapshot-stable and total-order deterministic, for example with (order_col, id) keyset pagination plus a captured high-water mark, or a repeatable-read transaction plus ORDER BY ..., dt.id.

File: api/src/export_worker.rs [hunk 2]
```diff
@@ -164,15 +165,54 @@ async fn execute_export_job(
...
+        heartbeat_cancel.cancel();
+        return;
+    }
+
+    let file_path = format!("{}/{}.{}", exports_dir, job_id, ext);
+
+    // Stream the export directly to disk. Peak per-job memory is bounded by
+    // `export_stream::PAGE_SIZE * per-record bytes`, not by total dataset
+    // size.
+    let result = write_export_to_file(
```
Comment (user1303836) [inline api/src/export_worker.rs:255]: [P1] write_export_to_file streams straight to the final exports/{job_id}.{ext} path, but heartbeat lease loss only stops the heartbeat task; it does not cancel this awaited write. A stale worker that resumes after claim_export_job reassigns the job can keep truncating/writing the same path as the new owner, and the error cleanup below can remove the new owner's artifact. update_or_abort catches the lost lease only after these side effects. Please propagate a lease-lost cancellation token into the page loop and/or write to attempt-scoped temp files and atomically publish only after an ownership-guarded transition.

File: api/src/export_stream.rs [hunk 3]
```diff
@@ -0,0 +1,440 @@
...
+                    $target_id,
+                    $network,
+                    $time_start,
+                    $time_end,
+                    PAGE_SIZE,
+                    offset,
+                )
+                .await?;
+            let n = records.len();
+            if n == 0 {
```
Comment (user1303836) [inline api/src/export_stream.rs]: [P2] CSV headers are only emitted inside write_page, but this break happens before write_page when the first page is empty. That turns an empty CSV export into a zero-byte file; the previous *_to_csv helpers always returned the header row, and CSV consumers rely on that schema even with zero records. Emit the header once before paging for CSV, or special-case total == 0 before flushing.

File: api/src/export_worker.rs [hunk 4]
```diff
@@ -277,30 +262,54 @@ async fn execute_export_job(
...
-                            };
-                            match sink.deliver(&body, &delivery_meta).await {
-                                Ok(receipt) => Ok(receipt.destination),
-                                Err(e) => {
-                                    warn!(job_id = %job_id, error = %e, "Sink delivery failed");
-                                    Err(format!(
-                                        "Exported {} records, but sink delivery failed: {e}",
-                                        record_count
-                                    ))
+                        Ok(sink) => match tokio::fs::read(&file_path).await {
```
Comment (user1303836) [inline api/src/export_worker.rs]: [P2] Sink-backed exports still read the whole artifact into memory before delivery, so any job with sink_config can still hit the OOM class this change is meant to remove. The row cap is not a byte cap, especially for event_details/raw JSON datasets. If this is intentionally a follow-up, I would avoid calling the export worker memory-bounded for sink jobs; otherwise the sink trait should accept a file path/stream so delivery preserves the bounded-memory property too.

**Review by user1303836 — COMMENTED** [review]
I found a few correctness blockers in the streaming export path. The main issue is that this moves export generation from one statement snapshot to repeated paged reads, so pagination and ownership semantics need to be made durable before merge.

**Comment by user1303836** [comment]
Pushed [ea31447](https://github.com/user1303836/spectraplex/commit/ea31447) addressing all four comments. Summary:

**[P1] Snapshot-stable pagination** — `Repository::stream_export_snapshot` now opens a `SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY` Postgres transaction and runs every page query through it via a dedicated `stream_paged_in_tx` helper. Pages are pushed through an `mpsc::channel(2)` into the disk-writer task so backpressure throttles the DB snapshot to disk speed. `build_dataset_filter_query` also gains a `dt.id DESC` tiebreaker so (order_col, id) is total-order deterministic — no more page shuffling on tied timestamps even under the snapshot.

**[P1] Lease-aware publish** — exports are now streamed to an attempt-scoped temp path `{job_id}.{worker_hash}.{ext}.tmp` instead of the canonical download path. A dedicated `lease_lost` `CancellationToken` is threaded from the heartbeat task into `stream_export_snapshot` (checked before every query and every send) and into the publish step. The atomic `fs::rename(temp → final)` only runs after a lease-holder-confirming `update_export_job_status(..., worker_id)` returns `Ok(true)`. If the heartbeat flips `lease_lost` or the update returns `Ok(false)` the stale worker unlinks its temp and exits without ever touching the canonical path. The no-sink path has an extra safety: if the final update returns `Err(())` after the rename (narrow race), it unlinks `final_path` so a reclaiming worker doesn't hand out the stale artifact via `/download`. Failure paths unlink only the attempt-scoped temp.

**[P2] Empty CSV header** — `write_export_to_file` now emits the CSV header once before the page loop, so a zero-record CSV export is a valid header-only file. JSONL zero-row exports correctly remain empty. Matches the old `*_to_csv` header-on-empty behavior.

**[P2] Bounded-memory sink delivery** — `ExportSink` trait now exposes `deliver_from_file(path, metadata)` with a default impl that reads-into-`Vec<u8>`-then-calls-`deliver` for backward compatibility. `LocalFileSink` overrides it with a streaming `std::io::copy` (via `spawn_blocking`, `O_NOFOLLOW` on both source and destination). `WebhookSink` overrides it using `tokio_util::io::ReaderStream` wrapped in `reqwest::Body::wrap_stream` with a preflighted `Content-Length` header. The worker calls `deliver_from_file` after the atomic publish, so sink delivery peak memory is now bounded by the `ReaderStream` buffer regardless of artifact size.

Cargo deps touched: `adapters` gains `tokio-util = "0.7"` (for `CancellationToken` in `stream_export_snapshot`); `api` gains the `io` feature on `tokio-util` and the `stream` feature on `reqwest`.

Verification: `cargo check --workspace --all-targets`, `cargo clippy --workspace --all-targets -- -D warnings`, `cargo fmt --all --check` all clean; `cargo test --workspace --lib --bins` passes 1104 tests (CSV format-preserving tests unchanged). Docker-backed integration tests couldn't be run on this machine; relying on CI to exercise the REPEATABLE READ snapshot and the attempt-scoped publish semantics against real Postgres.

File: adapters/src/v2_repo.rs [hunk 5]
```diff
@@ -1158,6 +1158,140 @@ pub fn build_dataset_completeness_upsert(
...
+            .map(&row_fn)
+            .collect::<anyhow::Result<Vec<_>>>()?;
+
+        // A second cancel check immediately before the blocking send so
+        // a lost lease can't push one more page to the consumer.
+        if cancel.is_cancelled() {
+            anyhow::bail!("export snapshot cancelled (lease lost or worker shutdown)");
+        }
+
+        if tx_out.send(batch_fn(records)).await.is_err() {
```
Comment (user1303836) [inline adapters/src/v2_repo.rs]: [P1] This send is not cancellation-aware. If the disk writer fails while the channel is full, write_export_to_file cancels the token and awaits the producer task, but page_rx is still alive and no longer being polled, so this send can wait forever. That leaves the export job heartbeating and the REPEATABLE READ transaction open instead of failing/cleaning up. Please make the send a tokio::select! against cancel.cancelled(), or explicitly drop the receiver before awaiting the producer after a write-loop error.

File: api/src/export_worker.rs [hunk 6]
```diff
@@ -366,14 +453,46 @@ async fn execute_export_job(
...
+                // No sink. Publish + mark completed.
+                //
+                // Order: we do the rename first (best-effort) and then
+                // update the job row. If the update fails because our
+                // lease was lost in this narrow window, the
+                // `update_or_abort(Err(()))` branch below unlinks the
+                // just-published final_path so a reclaiming worker
+                // does not hand out our artifact via `/download`. This
+                // mirrors the pre-publish lease check above.
+                if let Err(e) = tokio::fs::rename(&temp_path, &final_path).await {
```
Comment (user1303836) [inline api/src/export_worker.rs:492]: [P1] The no-sink path still publishes before a lease-guarded DB update. If this worker has been reclaimed but its heartbeat has not observed Ok(false) yet, it can rename its temp file over the canonical artifact; when the subsequent update_or_abort returns false, best_effort_unlink(final_path) can also delete the new owner's artifact. Please use the same lease-confirming pre-publish transition as the sink path, or another ownership-guarded publish step, before renaming to the canonical path.

**Review by user1303836 — COMMENTED** [review]
The original pagination/header/sink-memory concerns are mostly addressed in the new shape, but I found two remaining correctness blockers in the cancellation and publish paths.

**Review by user1303836 — COMMENTED** [review]
Re-reviewed the updated head. The earlier streaming/export correctness concerns look addressed: pagination is now snapshot-stable with deterministic `dt.id` tiebreaking, writes go through attempt-scoped temp artifacts, both publish paths now perform a lease-confirming `delivering` transition before rename, CSV headers are emitted before paging, bounded channel sends are cancellation-aware, and sink delivery now uses file/stream based delivery instead of rebuilding the whole artifact in memory.

I resolved the addressed threads. Remaining blocker is CI rather than a new export-path finding: Clippy and Cargo Audit are failing because this branch has not picked up the companion security/dependency and Clippy fixes yet. Merge that branch first and then update/rebase this one, or cherry-pick the same lockfile/audit/clippy fixes here before merging.
